//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelPlayaParadise.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Check_in_Out
    {
        public int Check_in_Out_ID { get; set; }
        public Nullable<int> Cliente_ID { get; set; }
        public Nullable<int> Habitacion_ID { get; set; }
        public Nullable<System.DateTime> Fecha_Check_in { get; set; }
        public Nullable<System.DateTime> Fecha_Check_out { get; set; }
    
        public virtual Clientes Clientes { get; set; }
        public virtual Habitaciones Habitaciones { get; set; }
    }
}
