//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelPlayaParadise.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Compras_Servicios_Adicionales
    {
        public int Compra_Servicio_ID { get; set; }
        public Nullable<int> Reservacion_ID { get; set; }
        public Nullable<int> Servicio_ID { get; set; }
        public Nullable<System.DateTime> Fecha_Hora { get; set; }
        public Nullable<int> Cantidad { get; set; }
    
        public virtual Reservaciones Reservaciones { get; set; }
        public virtual Servicios_Adicionales Servicios_Adicionales { get; set; }
    }
}
