//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelPlayaParadise.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Eventos
    {
        public int Evento_ID { get; set; }
        public string Nombre_Evento { get; set; }
        public Nullable<System.DateTime> Fecha_Hora { get; set; }
        public string Descripcion { get; set; }
    }
}
