//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelPlayaParadise.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Registros_Actividad_Intermediario
    {
        public int Registro_Intermediario_ID { get; set; }
        public Nullable<int> Intermediario_ID { get; set; }
        public Nullable<int> Empleado_ID { get; set; }
        public string Rol { get; set; }
        public Nullable<System.DateTime> Fecha_Hora_Actividad { get; set; }
        public string Tipo_Actividad { get; set; }
    
        public virtual Empleados Empleados { get; set; }
        public virtual Intermediarios Intermediarios { get; set; }
    }
}
