//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelPlayaParadise.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Registros_Actividad_Cliente
    {
        public int Registro_ID { get; set; }
        public Nullable<int> Cliente_ID { get; set; }
        public Nullable<System.DateTime> Fecha_Hora_Actividad { get; set; }
        public string Tipo_Actividad { get; set; }
    
        public virtual Clientes Clientes { get; set; }
    }
}
